const express = require("express")
const router = express.Router()
const Middleware = require("../Middleware/Tokenverify")
const AdminverifyToken = require("../Middleware/Admintokenverify")
const productController = require("../Controller/ItemController")
router.get("/getProduct/idforstat/:userID",Middleware,productController.getProduct)
router.get("/getProduct/:userID",Middleware,productController.getuserProduct)
router.get("/getProduct/Details/:productId",Middleware,productController.productDetails)
router.get("/getProduct/adminproduct/:adminID",AdminverifyToken,productController.getadminProduct)
router.put("/getProduct/:ids",Middleware,productController.updateProduct)
router.put("/getProduct/updateadminproduct/:ids",AdminverifyToken,productController.updateProduct)
router.post("/addProduct",Middleware,productController.adduserProduct)
router.post("/admin/addProduct",AdminverifyToken,productController.addadminProduct)
router.delete("/getProduct/deleteProduct/:id",Middleware,productController.deleteProduct)
router.delete("/getProduct/deleteadminProduct/:id",AdminverifyToken,productController.deleteadminProduct)
router.get("/getProduct/bycategory/:userID",Middleware,productController.getsearchProduct)
router.get("/getProduct/particular/:userID",Middleware,productController.getcategoryproduct)
module.exports = router