const express = require("express")
const router = express.Router()
const Middleware = require("../Middleware/Tokenverify")
const AdminverifyToken = require("../Middleware/Admintokenverify")
const uploadImage = require('../Config/Multer-config');
const userController = require("../Controller/UserController")
router.post("/UserRegistration",uploadImage,userController.registerUser)
router.post("/SellerRegistartion",Middleware,uploadImage,userController.sellerregister)
router.put("/SellerRegistartion/Approves/:id",AdminverifyToken,userController.updatesellerpending)
router.put("/SellerRegistartion/modify/:userID",Middleware,userController.alternotify)
router.get("/SellerRegistartion",AdminverifyToken,userController.getsellerdata)
router.get("/SellerRegistartion/pendingstatus/:userID",Middleware,userController.getsellerpendingstatus)
router.get("/SellerRegistartion/notify/:userID",Middleware,userController.onlynotify)
router.delete("/SellerRegistartion/:id",AdminverifyToken,userController.deletesellerpending)
router.get("/UserRegistration",AdminverifyToken,userController.getUsers)
router.delete("/UserRegistration/:userID",AdminverifyToken,userController.deleteUsers)
router.post("/Login",userController.loginuser)
router.post("/Login/passwordConfirm/:userID",Middleware,userController.passConfirm)
router.put("/Login/newpassword/:userID",Middleware,userController.newPass)
router.put("/Login/Update/:userID",Middleware,userController.editUser)
router.put("/UserRegistration/:userID",AdminverifyToken,userController.updateenotify)
router.put("/UserRegistration/ban/:userID",AdminverifyToken,userController.updateban)
router.put("/UserRegistration/user/:userID",Middleware,userController.updatenotifyuser)
router.put("/Login/Picture/:userID",uploadImage,userController.editPic)
router.get("/Login/profile/:userID",userController.getUserprofile)
router.get("/Liked/:userID",Middleware,userController.fetchLiked)
router.put("/Liked/delete/:userID",Middleware,userController.updatelike)
router.put("/Liked/add/:userID",Middleware,userController.addtowishlist)
router.get("/Liked/full/:userID",Middleware,userController.getuserwishlist)
router.put("/Cart/:userID",Middleware,userController.addtoCart)
router.get("/Cart/ids/:userID",Middleware,userController.getuserCartid)
router.get("/Cart/items/:userID",Middleware,userController.getuserCartitem)
router.put("/Cart/remove/:userID",Middleware,userController.removefromcart)
router.put("/Cart/updateQuantity/:userID",Middleware,userController.updatequantity)
module.exports = router